language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - 2.1.1
  - ruby-head
addons:
  code_climate:
  	repo_token: fdcf6734058cf96fbb136bf50a755e9011bbc93ffed08e0c5717b9c025166c45
script: rspec spec